config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations', 
                                    passwords: 'users/passwords'
                                  }
  
  devise_scope :user do
    root to: 'users/sessions#new'
  end

  resources :user , only: [] do
    resources :todo_items, only: [:index, :create] 
  end

  resources :todo_items, only: [:destroy]  do
    collection do
      patch :sort
    end
    member do
      patch :complete       
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord

  #Validations
  validates :description, presence: true
  
  #Associations
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #Associations
  has_many :todo_items, -> { order(position: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :require_login

	private
		def require_login
			unless current_user.present?
				flash[:error] = "Log in first"
				redirect_to root_path
			end
		end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_user, only: [:index, :create]
	before_action :set_todo_item, only: [:destroy, :complete]

	def index
		@todo_items = @user.todo_items
	end

	def create
		@todo_item = @user.todo_items.build(todo_item_params)
		@todo_item.save
		@todo_items = @user.todo_items
	end

	def destroy
		@todo_item.destroy ? flash[:notice] = "Todo Item Deleted" : flash[:alert] = "Unable to delete todo item"
		redirect_to user_todo_items_path(current_user)
	end

	def sort
		params[:todo_item].each_with_index do |id, index|
			TodoItem.where(id: id).update_all(position: index + 1)
		end
		head :ok
	end

	def complete
		@todo_item.update_attribute('completed_at', Time.now)
		render :json => { :completed_at => @todo_item.completed_at.strftime('%d %b, %Y'), :success => true }
	end

	private
		def set_user
			@user = User.find_by_id(params[:user_id])
			return true if @user.present?
			flash[:alert] = "User not found"
			redirect_to root_path
		end

		def set_todo_item
			@todo_item = TodoItem.find_by_id(params[:id])
			return true if @todo_item.present?
			flash[:alert] = "Item not found"
			redirect_to user_todo_items_path(current_user)
		end

		def todo_item_params
      params.require(:todo_item).permit(:description, :due_date)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_before_action :require_login
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	skip_before_action :require_login, only: [:new, :create]
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	skip_before_action :require_login, only: [:new, :create]
	
	protected  
		def after_sign_in_path_for(resource)
			user_todo_items_path(resource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
	ALERT_TYPES = [:danger, :info, :success, :warning, :error] unless const_defined?(:ALERT_TYPES)

	def bootstrap_flash
		flash_messages = []
		flash.each do |type, message|
			# Skip empty messages, e.g. for devise messages set to nothing in a locale file.
			next if message.blank?

			type = type.to_sym
			type = :success if type == :notice
			type = :danger  if (type == :alert || type == :error)
			next unless ALERT_TYPES.include?(type)
			
			Array(message).each do |msg|
				text = content_tag(:div,
														content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
																msg.html_safe, :class => "alert alert-#{type}")
				flash_messages << text if msg
			end
		end
		flash_messages.join("\n").html_safe
	end
end
  

app/helpers/todo_item_helper.rb
module TodoItemHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApplication
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"}]
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
  %body
    = render 'shared/nav_bar'
    .content-wrapper
      .flash-messages-div
        = bootstrap_flash
      = yield

app/views/shared/_nav_bar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo03", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo03", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{:href => "/"} TODO
  #navbarTogglerDemo03.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      %li.nav-item
        - if !user_signed_in? && devise_mapping.registerable? && controller_name != 'registrations'
          = link_to "Sign Up", new_registration_path(resource_name), class: 'nav-link'
      %li.nav-item
        - if user_signed_in?
          = link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link'
        - elsif controller_name != 'sessions' 
          = link_to "Log in", new_session_path(resource_name), class: 'nav-link'

app/views/todo_items/_form.html.haml
.new-task-section.p-5
  %h5 Add new Task
  = form_with(model: TodoItem.new(), url: user_todo_items_path(current_user), html: {class: ' new-todo-form'}) do |f|
    .form-group.mr-3
      = f.text_field :description, placeholder: "New Todo", class: 'form-control col-md-6'
    .form-group.mr-3
      = f.text_field :due_date, placeholder: 'Due Date', class: "form-control datepicker col-md-6", readonly: true
    .form-group.mr-3
      = f.submit "Add" , class: 'form-control btn btn-primary col-md-6'

app/views/todo_items/_todo_item.html.haml
%tr{id: dom_id(todo_item), :class => "#{todo_item.completed? ? 'completed-item': ''}"}
	%td=todo_item.description
	%td=todo_item.due_date.present? ? todo_item.due_date.strftime('%d %b, %Y') : ''
	%td.completed-date=todo_item.completed_at.present? ? todo_item.completed_at.strftime('%d %b, %Y') : ''
	%td
		- if todo_item.completed?
			= link_to "Completed", "#", class: 'btn btn-success btn-sm mar-l-10 disabled-link'
			= link_to "Delete", "#", class: 'btn btn-danger btn-sm mar-l-10 disabled-link'
		- else
			= link_to "Mark Completed", "#", data: {url: complete_todo_item_path(todo_item)}, class: 'mark-complete btn btn-info btn-sm mar-l-10 action-button'
			= link_to "Delete", todo_item_path(todo_item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mar-l-10 action-button'

app/views/todo_items/create.js.erb
<% if @todo_item.persisted? %>
  $('#todo_items').html("<%= j render @todo_items %>");
  $(".new-todo-form")[0].reset();
  $(".no-tasks").text('')
<% end %>

app/views/todo_items/index.html.haml
.row
  .col-md-10
    %table.table.table-striped.table-bordered.table-hover.table-condensed
      %thead
        %tr
          %th Task
          %th Due Date
          %th Completed Date
          %th Actions
      %tbody#todo_items{"data-url" => sort_todo_items_path}
        = render @todo_items
    - if @todo_items.blank?
      .no-tasks No Tasks Added yet, Add one now!!
    = render 'form'